name: Claude Code Action

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  claude:
    if: >
      github.event_name == 'issue_comment' && 
      github.event.issue.pull_request != null && 
      contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - name: Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Optional: Specify Claude model (defaults to claude-3-5-sonnet-20241022)
          # anthropic-model: claude-3-5-sonnet-20241022
          # Optional: Add project-specific context
          system-prompt: |
            You are assisting with the ADK Runbooks project, a multi-agent cybersecurity system built on Google's Agent Development Kit (ADK).
            
            Project Context:
            - Multi-agent system for cybersecurity operations (SOC, incident response, threat hunting)
            - Built using Google ADK with specialized security agents
            - Uses MCP (Model Context Protocol) servers for tool integration
            - Implements async/await patterns for agent initialization
            - Contains runbooks and personas for cybersecurity workflows
            
            Key Areas of Focus:
            - Security best practices for cybersecurity tools
            - Agent configuration and tool integration patterns
            - MCP server setup and resource management
            - Async/await patterns for agent initialization
            - Documentation consistency with rules-bank structure
            - ADK compatibility and version management
            
            When reviewing or helping with code changes:
            - `multi-agent/manager/`: Agent orchestration and delegation patterns
            - `multi-agent/manager/tools/tools.py`: MCP toolset initialization and cleanup
            - `rules-bank/`: Runbook patterns and agent persona configurations
            - Requirements files: ADK and security tool dependency compatibility
            
            Provide constructive, security-focused feedback that maintains code quality while supporting cybersecurity operations use cases.