name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'rules-bank/**' # Trigger on changes within the rules-bank (source) directory
      - 'Makefile' # Trigger if the main Makefile changes
      - 'requirements-docs.txt' # Trigger if Python dependencies change
  workflow_dispatch: # Allows manual triggering

# Required for GitHub Pages API deployment
permissions:
  contents: read
  pages: write  # Needed to push to gh-pages branch
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a specific version if needed, e.g., 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Assuming requirements are in requirements-docs.txt in the root
          if [ -f requirements-docs.txt ]; then
            pip install -r requirements-docs.txt
          else
            echo "requirements-docs.txt not found. Please ensure it exists in the repository root."
            # Fallback to install core dependencies if file is missing, though it should exist
            pip install sphinx myst-nb sphinx-book-theme sphinx-copybutton sphinx-design sphinxcontrib-mermaid linkify-it-py sphinx-autodoc-typehints
          fi

      - name: List files for debugging
        run: |
          ls -R .
          echo "--- rules-bank content ---"
          ls -R rules-bank || echo "rules-bank directory not found at root"
          echo "--- content of rules-bank/conf.py ---"
          cat rules-bank/conf.py || echo "rules-bank/conf.py not found"
          echo "--- end listing ---"

      - name: Build documentation
        run: |
          # Run make html from the repository root
          # The Makefile is configured with SOURCEDIR=rules-bank and BUILDDIR=build
          make html

      - name: Create .nojekyll file in output directory
        run: |
          touch build/html/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/html

  deploy:
    needs: build-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
